language: node_js

node_js:
  - "14"

dist: xenial

service: docker

script:
  - echo 'Build Starts!'
  - echo 'Running Test!'
  - npm test
  - npm run build
  - docker build -t modanisa-todo-frontend .
  - docker images
